### ISSUE TITLE
What's your take on the Pocket controversy?

### ISSUE THREAD

**Issue by mollikka** [jedireza/ama#10]
Mozilla bundled a client of the closed-source tool Pocket directly into Firefox. Open-source activists criticized it, but Mozilla maintains that it didn't violate OSS ethics. What do you personally think about the whole debacle?

**Comment by jedireza** [comment]
:wink: I don't see this as "controversy" or "debacle".

I don't use Pocket myself, I just moved the icon out of my toolbar and forgot about it. Change is a part of the Web and software development. What can be done can also be undone. No matter how this specific situation ends up, it will be a valuable learning experience for everyone involved.
