### ISSUE TITLE
Why people stress to use Immutable structures in javascript ?

### ISSUE THREAD

**Issue by asvny** [jedireza/ama#11]

**Comment by jedireza** [comment]
I haven't used immutable structures that much in my work. My understanding of immutable structures is shallow. Most of what I know about them is what I've read.

From the [Immutable.js website](http://facebook.github.io/immutable-js/):

> Immutable data cannot be changed once created, leading to much simpler application development, no defensive copying, and enabling advanced memoization and change detection techniques with simple logic.

From the [React.js docs](https://facebook.github.io/react/docs/advanced-performance.html#immutable-js-to-the-rescue):

> Immutability makes tracking changes cheap; a change will always result in a new object so we only need to check if the reference to the object has changed.

Some other links you may find helpful:
- [Why immutable collections?](https://scott.mn/2014/04/27/why_immutable_collections/)
- [Benefits of Immutable.js](https://discuss.reactjs.org/t/benefits-of-immutable-js/435/2)
