### ISSUE TITLE
What thing you made are you most proud of? 

### ISSUE THREAD

**Issue by hackerkid** [jedireza/ama#17]

**Comment by jedireza** [comment]
**Software:** The [`hapi-mongo-models`](https://github.com/jedireza/hapi-mongo-models/) module that's used in [Frame](https://github.com/jedireza/frame/) and [Aqua](https://github.com/jedireza/aqua/)

**Mentoring:** helping to build and organize the [NodeSchool San Francisco](http://nodeschool.io/sanfrancisco/) chapter.

**Artistically:** [Photos](https://500px.com/jedireza), many of which are not online.
