### ISSUE TITLE
What's the best book you ever read? 

### ISSUE THREAD

**Issue by hackerkid** [jedireza/ama#18]

**Comment by jedireza** [comment]
It's hard to say one is best. A few that come to mind are:
- [The Hard Thing About Hard Things](http://www.amazon.com/The-Hard-Thing-About-Things/dp/0062273205) - Ben Horowitz
- [Zero to One](http://www.amazon.com/Zero-One-Notes-Startups-Future/dp/0804139296) - Peter Thiel
- [Nonviolent Communication](http://www.amazon.com/Nonviolent-Communication-A-Language-Life/dp/1892005034) - Marshall B. Rosenberg
