### ISSUE TITLE
What is your opinion on the AMP project?

### ISSUE THREAD

**Issue by claudiopro** [jedireza/ama#21]

**Comment by jedireza** [comment]
By AMP do you mean https://www.ampproject.org/, https://github.com/ampproject/amphtml?

If so, yeah, this is the second time I've seen this and the first time I've looked at the GitHub repo (quickly). I skim liberally, so I may miss things, but in general it sounds like an interesting idea. I see it as a bunch of publishers using one CDN and agreeing to a base set of functionality/components.

Thanks for bringing this up, I'll need to look into this more when I get more time.

**Comment by claudiopro** [comment]
Yes, that's it. Cheers, I'm really curious to see how the industry is going to receive this web-compatible take on performance optimization for publishers and advertisers.
