### ISSUE TITLE
What kind of programming are you into?

### ISSUE THREAD

**Issue by sindresorhus** [jedireza/ama#5]
You co-Organize NodeSchoolSF, so I know you do Node.js. Any other languages/platforms you're excited about?

**Comment by jedireza** [comment]
I became a programming polyglot early on and the majority of my career has been related to Web development (server and client).

Lately my interests have been pulling me toward lower level systems programming. I'd like to spend more time with Go and/or Rust. Maybe one day I'll scratch my itch and create a web crawler or a data miner of some kind.

**Comment by sindresorhus** [comment]
> I'd like to spend more time with Go and/or Rust.

:+1: [Ditto](https://github.com/sindresorhus/ama/issues/7).
