### ISSUE TITLE
What's your keyboard/mouse?

### ISSUE THREAD

**Issue by insanehong** [jedireza/ama#9]

**Comment by jedireza** [comment]
Ahhh the meaty questions :+1:

I'm using a [Das Keyboard Model S Ultimate](http://www.daskeyboard.com/model-s-ultimate/) (brown mx) and an [Apple Magic Mouse](https://www.apple.com/magicmouse/).

![das_magic](https://cloud.githubusercontent.com/assets/979929/8752430/d44090de-2c68-11e5-9f3d-7c3700f02336.jpg)
